#!/bin/bash

echo 'gStyle->SetOptFit();TH2D*h2=(TH2D*)(AliAnalysisTaskCalibEmcal->Get("histogram")->FindObject("_histogram_cell_id_pi0_mass"));h2->GetYaxis()->SetTitle("m_{\\gamma\\gamma}\\:(\\mathrm{GeV}/c^2)");h2->Draw("colz");gApplication->Run();' | root -l "$1"
